# Generated by Django 2.1.4 on 2019-01-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getuserinfo', '0002_userinfo_regist_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userid',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='用户id'),
        ),
    ]
