# Generated by Django 2.1.4 on 2019-01-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getuserinfo', '0004_auto_20190102_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='openId',
            field=models.CharField(default='', max_length=100, verbose_name='用户openid'),
        ),
    ]
