# Generated by Django 2.1.4 on 2019-01-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getuserinfo', '0005_auto_20190102_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用户id'),
        ),
    ]
