# Generated by Django 2.1.4 on 2019-01-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userid', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='用户id')),
                ('openId', models.CharField(max_length=100, verbose_name='用户openid')),
                ('nickName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='用户昵称')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='所在城市')),
                ('avatarUrl', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
