# Generated by Django 2.1.4 on 2019-01-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_openid_session'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
