# Generated by Django 2.1.4 on 2019-06-03 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0002_topicprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprofile',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='提交时间'),
            preserve_default=False,
        ),
    ]
