# Generated by Django 2.1.4 on 2019-06-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artical', '0003_topicprofile_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='articalcommentprofile',
            name='adopt',
            field=models.IntegerField(blank=True, choices=[(0, '未审核'), (1, '审核通过'), (2, '审核不通过')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='articalprofile',
            name='adopt',
            field=models.IntegerField(blank=True, choices=[(0, '未审核'), (1, '审核通过'), (2, '审核不通过')], default=0, null=True),
        ),
    ]
