# Generated by Django 2.1.4 on 2019-01-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('getuserinfo', '0006_auto_20190102_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticalCommentProfile',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('comment_type', models.CharField(default='对文章', max_length=10, verbose_name='评论类型')),
                ('comment_imgurl', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='评论中的图片url')),
                ('comment_content', models.CharField(blank=True, default='', max_length=5000, null=True, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论提交时间')),
            ],
            options={
                'verbose_name': '对文章的评论',
                'verbose_name_plural': '对文章的评论',
            },
        ),
        migrations.CreateModel(
            name='CommentCommentProfile',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论id')),
                ('comment_type', models.CharField(default='对评论', max_length=10, verbose_name='评论类型')),
                ('comment_imgurl', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='评论中的图片url')),
                ('comment_content', models.CharField(blank=True, default='', max_length=5000, null=True, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论提交时间')),
                ('comment_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artical.ArticalCommentProfile', verbose_name='评论的评论id')),
                ('sender', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='getuserinfo.UserInfo', verbose_name='发送者')),
            ],
            options={
                'verbose_name': '对评论的评论',
                'verbose_name_plural': '对评论的评论',
            },
        ),
        migrations.CreateModel(
            name='DeclareProfile',
            fields=[
                ('declareid', models.AutoField(primary_key=True, serialize=False, verbose_name='表白内容id')),
                ('towho', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='接受者')),
                ('anonymous', models.IntegerField(blank=True, choices=[(1, '匿名'), (0, '不匿名')], default=0, null=True, verbose_name='是否匿名')),
                ('imgurl', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='图片url')),
                ('content', models.CharField(blank=True, default='', max_length=5000, null=True, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('sender', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='getuserinfo.UserInfo', verbose_name='发送者')),
            ],
            options={
                'verbose_name': '表白信息',
                'verbose_name_plural': '表白信息',
            },
        ),
        migrations.AddField(
            model_name='articalcommentprofile',
            name='comment_artical_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artical.DeclareProfile', verbose_name='评论的文章id'),
        ),
        migrations.AddField(
            model_name='articalcommentprofile',
            name='sender',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='getuserinfo.UserInfo', verbose_name='发送者'),
        ),
    ]
