# Generated by Django 2.1.4 on 2019-05-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('openId', models.CharField(default='', max_length=100, verbose_name='用户openid')),
                ('nickName', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='用户昵称')),
                ('gender', models.IntegerField(blank=True, choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='所在城市')),
                ('avatarUrl', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='头像')),
                ('age', models.IntegerField(blank=True, default=18, max_length=3, null=True, verbose_name='用户年龄')),
                ('major', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='专业')),
                ('studentId', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='学号')),
                ('regist_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
