# Generated by Django 2.1.4 on 2019-05-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getuserinfo', '0002_auto_20190522_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='用户年龄'),
        ),
    ]
