# Generated by Django 2.1.4 on 2019-06-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getuserinfo', '0004_admininfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '普通用户信息', 'verbose_name_plural': '普通用户信息'},
        ),
    ]
