# Generated by Django 2.1.4 on 2019-06-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='messageObj',
            new_name='message',
        ),
    ]
